from .carp import Carp
from .catfish import Catfish
from .copperhead import Copperhead
from .coralsnake import CoralSnake
from .cottonmouth import Cottonmouth
from .crocodile import Crocodile
from .donkey import Donkey
from .goat import Goat
from .llama import Llama
from .monkey import Monkey
from .python import Python
from .rattlesnake import RattleSnake
from .seal import Seal
from .tiger import Tiger
from .turtle import Turtle